import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
// import Header from '@/components/header'
// import { Comforter } from 'next/font/google'
import Link from 'next/link'
import Header from '@/components/header'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin']
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin']
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

// const comforter = Comforter({ subsets: ['latin'], weight: '400' })

export default function RootLayout({
  children,
  team,
  analytic,
  modal
}: Readonly<{
  children: React.ReactNode
  team: React.ReactNode
  analytic: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
      <body>
        {/* <body className={comforter.className}> */}
        {/* Hello 大家好，这里是根Layout */}
        {/* <Header/>        */}
        <div className="container max-auto p-4">
          <div className="flex justify-center text-blue-500 p-6 gap-6">
            <Link href="/">Home</Link>
            <Link href="/visitor">Visitor</Link>
          </div>
          <div className="flex gap-6">
            {team}
            {analytic}
          </div>
        </div>
        <Header />
        {children}
        {modal}
      </body>
    </html>
  )
}
