// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
"use client"
import Link from "next/link";
import { useState } from "react";
import { usePathname } from "next/navigation";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const [count, setCount] = useState(0);
    const pathname = usePathname();
    console.log(pathname);
  return (
    <div className="border-2 border-dashed border-black mx-auto p-4 w-1/2 mt-2">
        我是DashboardLayout
        <div className="flex gap-4 font-bold text-lg mb-4">
            <Link href="/dashboard/about" className={pathname==='/dashboard/about'?'text-purple-500':''}>About</Link>
            <Link href="/dashboard/settings" className={pathname==='/dashboard/settings'?'text-purple-500':''}>Settings</Link>
            <h2>dashboard Layout {count}</h2>
            <button className="bg-black text-white p-2 my-4 rounded-md" onClick={()=>setCount(count + 1)}>增加</button>
        </div>
        {children}
    </div>
  );
}
