// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
"use client"
import Link from "next/link";
import { useState } from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardTemplate({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const [count, setCount] = useState(0);
  return (
    <div className="border-2 border-dashed border-black mx-auto p-4 w-1/2 mt-2">
        <div className="flex gap-4 font-bold text-lg mb-4 text-purple-500">
            {/* <Link href="/dashboard/about">About</Link>
            <Link href="/dashboard/settings">Settings</Link> */}
            <h2>dashboard Template {count}</h2>
            <button className="bg-black text-white p-2 my-4 rounded-md" onClick={()=>setCount(count + 1)}>增加</button>
        </div>
        {children}
    </div>
  );
}
